global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - 'alert_rules.yml'

scrape_configs:
  - job_name: 'chores-dev'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8001']
        labels:
          environment: 'dev'

  - job_name: 'chores-prod'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8000']
        labels:
          environment: 'prod'
